@startuml
package CommunityMeetingPlatform {

[Frontend] as WebClient
[API Gateway] as ApiGateway
[User Access Service] as UserAccess
[Registrations Service] as Registrations
[Group Proposal Service] as GroupProposalService
[Group Management Service] as GroupService
[Meeting Management Service] as MeetingService
[Payment Processing Service] as PaymentService
[External Payment Gateway] as PaymentGateway
[Notification Service] as NotificationService
[Database] as Database

WebClient --> ApiGateway

ApiGateway --> UserAccess
ApiGateway --> Registrations
ApiGateway --> GroupProposalService
ApiGateway --> GroupService
ApiGateway --> MeetingService
ApiGateway --> PaymentService
ApiGateway --> NotificationService

UserAccess --> Database
Registrations --> Database
GroupProposalService --> Database
GroupService --> Database
MeetingService --> Database
PaymentService --> Database
NotificationService --> Database

GroupProposalService --> GroupService
MeetingService --> GroupService
MeetingService --> PaymentService
PaymentService --> PaymentGateway
PaymentService --> GroupService
PaymentService --> NotificationService
GroupService --> NotificationService
MeetingService --> NotificationService

}
@enduml
