@startuml
package ECommerceSystem {

    [Frontend]          as Frontend
    [API]           as API
    [SessionService]       as Session

    [Catalog]       as Catalog
    [Cart]          as Cart
    [CheckoutService]      as Checkout
    [PaymentService]       as Payment
    [ShippingService]      as Shipping
    [CurrencyService]      as Currency
    [RecommendationService] as Recommend
    [AdNetworkService]   as Ads
    [EmailService]         as Email

    [RelationalDatabase]   as DB
    [Cache]           as Cache

    Frontend --> API
    API --> Session
    Session --> Cache

    API --> Catalog
    API --> Cart
    API --> Checkout
    API --> Currency
    API --> Recommend
    API --> Ads

    Catalog --> DB
    Catalog --> Cache
    Cart --> DB
    Cart --> Cache

    Checkout --> Cart
    Checkout --> Payment
    Checkout --> Shipping
    Checkout --> Email

    Payment --> DB
    Shipping --> DB
    Currency --> DB
    Recommend --> DB
    Ads --> DB
    Email --> SMTPServer

    DB --> Cache
}
@enduml
