@startuml
skinparam componentStyle rectangle

' Components
[Frontend] as WebClient
[API Gateway] as APIGateway
[User Service] as UserService
[Group Proposal Service] as GroupProposalService
[Group Management Service] as GroupService
[Meeting Service] as MeetingService
[Payment Service] as PaymentService
[Notification Service] as NotificationService
[Payment Gateway] as PaymentGateway
[Relational Database] as Database

' Client --> Entry point
WebClient --> APIGateway

' Gateway --> Internal Services
APIGateway --> UserService
APIGateway --> GroupProposalService
APIGateway --> GroupService
APIGateway --> MeetingService
APIGateway --> PaymentService
APIGateway --> NotificationService

' Services <-> Database
UserService --> Database
GroupProposalService --> Database
GroupService --> Database
MeetingService --> Database
PaymentService --> Database

' Logical Interactions
GroupProposalService --> UserService
GroupProposalService --> NotificationService

GroupService --> PaymentService
GroupService --> UserService

MeetingService --> PaymentService
MeetingService --> UserService
MeetingService --> NotificationService

PaymentService --> PaymentGateway
PaymentService --> NotificationService

NotificationService --> WebClient

@enduml
