@startuml
package ECommercePlatform {
[Frontend] as Frontend
[Catalog] as Catalog
[Cart] as Cart
[Checkout] as Checkout
[Payment] as Payment
[Shipping Estimator] as ShippingEstimator
[Currency] as Currency
[Recommendation] as Recommendation
[Email] as Email

Frontend --> Catalog
Frontend --> Cart
Cart --> Catalog
Frontend --> Checkout
Checkout --> Cart
Checkout --> Payment
Checkout --> ShippingEstimator
Checkout --> Email
Checkout --> Currency
Recommendation --> Catalog
Frontend --> Recommendation
Currency --> Catalog
ShippingEstimator --> Catalog
}
@enduml